/**
 * This script generates a TypeScript file that embeds Arial/ArialBD as base64 @font-face
 * in the SVG, so text renders on any environment (Cloud Run, Docker, etc) without needing
 * system fonts or external font files.
 */
const fs = require('fs');
const path = require('path');

const fontDir = path.join(__dirname, '..', 'fonts');

function toBase64(filename) {
  const p = path.join(fontDir, filename);
  if (!fs.existsSync(p)) {
    console.error(`MISSING: ${p}`);
    return null;
  }
  return fs.readFileSync(p).toString('base64');
}

const arialB64 = toBase64('arial.ttf');
const arialBdB64 = toBase64('arialbd.ttf');

if (!arialB64 || !arialBdB64) {
  console.error('Font files not found! Run from project root after placing fonts/ dir.');
  process.exit(1);
}

const output = `// AUTO-GENERATED by scripts/generate_font_ts.cjs — DO NOT EDIT MANUALLY
// Fonts embedded as base64 so SVG text always renders on headless Linux (Cloud Run)

export const ARIAL_B64 = "${arialB64}";
export const ARIAL_BOLD_B64 = "${arialBdB64}";

export function getFontFaceDefs(): string {
  return \`<style>
    @font-face {
      font-family: 'Arial';
      font-weight: normal;
      src: url('data:font/truetype;base64,\${ARIAL_B64}') format('truetype');
    }
    @font-face {
      font-family: 'Arial';
      font-weight: bold;
      src: url('data:font/truetype;base64,\${ARIAL_BOLD_B64}') format('truetype');
    }
  </style>\`;
}
`;

const outPath = path.join(__dirname, '..', 'services', 'embeddedFonts.ts');
fs.writeFileSync(outPath, output);
console.log(`Written ${Math.round(output.length / 1024)}KB to ${outPath}`);
